name: build and Release 

on:  
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout 
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn install
    
    - name: Run build
      run: yarn prepack
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false